---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: http-operator
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./config/default
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: http-operator
  targetNamespace: http-operator-system
  timeout: 3m0s
  wait: true
